version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - es-net
    ports:
      - "9200:9200"
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  filebeat:
    container_name: fb-container
    image: docker.elastic.co/beats/filebeat:7.11.0
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml:ro
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker:ro
        read_only: true
      - type: bind
        source:  /var/run/docker.sock
        target: /var/run/docker.sock

    networks:
      - es-net
    depends_on:
      - elasticsearch
    user: root
#    command: ["sh", "-c", "chmod go-w /usr/share/filebeat/filebeat.yml && /usr/share/filebeat/filebeat -e"]
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - es-net
volumes:
  elasticsearch_data:
networks:
  es-net:
    driver: bridge